""" add_impact_score

Revision ID: 5f13517aa12c
Revises: a9c465e453f8
Create Date: 2026-05-29 14:49:05.847190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f13517aa12c'
down_revision: Union[str, Sequence[str], None] = 'a9c465e453f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('impact_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'impact_score')
    # ### end Alembic commands ###
