"""add_upvotes_to_report

Revision ID: bf07e92699fd
Revises: 5f13517aa12c
Create Date: 2026-05-29 15:18:12.692053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf07e92699fd'
down_revision: Union[str, Sequence[str], None] = '5f13517aa12c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('upvotes', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'upvotes')
    # ### end Alembic commands ###
